---
- name: Play 2
  hosts: my 
  become: yes
  tasks:

  - name: tuned on
    apt: 
      name: 
        - tuned
      state: latest
      update_cache: yes

  - name: service tuned 
    ansible.builtin.service:
      name: tuned
      state: started
      enabled: yes